### ISSUE TITLE
Having issue logging-in/authentication

### ISSUE THREAD

**Issue by maniac-en** [fredluetkemeier/inkdrop-settings-sync#4]
Hi,

I'm using `Debian` OS and not able to authenticate with my GitHub account in this plugin.

`cat /etc/os-release`
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

## What happens?
- I start `Inkdrop` and get welcome screen<br>
![Screenshot from 2023-10-21 02-26-33](https://github.com/fredluetkemeier/inkdrop-settings-sync/assets/45049766/5173c316-c240-423a-bf39-bc423f5f9de1)<br>
- I click `Next` and get a screen that shows a `code` and nothing else happens after that<br>
![Screenshot from 2023-10-21 02-26-45](https://github.com/fredluetkemeier/inkdrop-settings-sync/assets/45049766/3d83b5aa-1326-44d1-bedb-84c5f9e1bcb0)<br>
- I also keep seeing this content on bottom-left as shown below:<br>
![Screenshot from 2023-10-21 02-27-00](https://github.com/fredluetkemeier/inkdrop-settings-sync/assets/45049766/2c241275-9604-4d0b-9292-d87462ee73b1)<br>

Can you please help me fix this? I might be missing something very basic, but some steps would be helpful, Thanks!

**Comment by fredluetkemeier** [comment]
First off, thanks for the detailed bug report! 

Sorry to hear you're having issues. This is definitely a bug. When you get to the auth code screen, the plugin is supposed to open GitHub's device login page: https://github.com/login/device

You can visit the above link directly and enter the plugin-provided code. 

I'll do some testing and try to get it working properly on Linux. If you run into any other issues after you get signed in, feel free to open additional issues. Thanks!

**Comment by maniac-en** [comment]
Works as expected for me 😃 
Thanks a ton for the fix! 🚀
